### PR TITLE
Bump base & bytestring bounds, include recent GHCs in CI config

### LINKED ISSUE #12: Bump bounds for base, bytestring and text
The bounds can be bumped to allow base-4.19, bytestring-0.12.0 and text-2.1.

The package builds without any further changes.

### PR DESCRIPTION
**Pull request by jhrcek**
Trying to resolve https://github.com/maoe/ghc-trace-events/issues/12

### CODE REVIEW

**Comment by maoe** [comment]
LGTM. Thanks for your contribution!

**Comment by ysangkok** [comment]
@maoe Would it be possible to make a release? Then he package could go back into Stackage Nightly.

**Comment by maoe** [comment]
Sure. Sorry for the delay. I'll make a new release today.

**Comment by maoe** [comment]
Released v0.1.2.8

**Pull request merged**
